export const LOCAL_STORAGE = {
    // 用户配置
    CONFIG: 'config',
    // 天气
    WEATHER_RESPONSE: 'WEATHER_RESPONSE',
    WEATHER_RESPONSE_LAST_TIME: 'WEATHER_RESPONSE_LAST_TIME',
    // IP定位
    IP_RESPONSE: 'IP_RESPONSE',
};
